# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/School/Spring 2018/ECEN 449/HW1/Q1/Q1.cache/wt} [current_project]
set_property parent.project_path {C:/School/Spring 2018/ECEN 449/HW1/Q1/Q1.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_cache_permissions disable [current_project]
read_verilog -library xil_defaultlib {{C:/School/Spring 2018/ECEN 449/HW1/Q1/hw1_q1.v}}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top hw1_q1 -part xc7z010clg400-1


write_checkpoint -force -noxdef hw1_q1.dcp

catch { report_utilization -file hw1_q1_utilization_synth.rpt -pb hw1_q1_utilization_synth.pb }
